image: java:8

pipelines:
  custom:
    - step:
      caches:
        - gradle
      script:
        - bash ./gradlew build
        - apt-get update
        - apt-get install zip
        - mv bundle EverSector
        - zip -r EverSector.zip EverSector
        - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"EverSector.zip"