image: java:8

pipelines:
  default:
    - step:
        caches:
          - gradle
        script:
          - bash ./gradlew build
          - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"bundle"